import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Healthtech - Redesigned for fun",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script id="animate" src="/js/app.js" />
      <Script id="calendly" src="https://assets.calendly.com/assets/external/widget.js" async />
    </html>
  );
}
